config/routes.rb
Rails.application.routes.draw do
  

  get 'signup'  => 'users#new'
  get 'show' => 'static_pages#show'
  get 'upload' => 'static_pages#upload'

  root 'static_pages#home'

end

app/models/user.rb
class User < ActiveRecord::Base
    before_save { self.email = email.downcase }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :name, presence: true, length: { maximum: 50 }
    validates :email, presence: true, length: { maximum: 255 }, 
                            format: { with: VALID_EMAIL_REGEX },
                            uniqueness: { case_sensitive: false}
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  def hello
    render text: 'Hello, Bears!'
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def show
  end

  def upload
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  
  def full_title(page_title = '')
    base_title = "Awesome Bear Gallery"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "AwesomeBearGallery", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Войти",   '#' %></li>
        <li><%= link_to "Смотреть",   show_path %></li>
        <li><%= link_to "Загрузить", upload_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>

<div class="container">
    <%= yield %>
</div>
</body>
</html>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Awesome Bear Gallery</h1>
  <p>Медвежья Галлерея - тестовый проект на Ruby on Rails.</p>
  <%= link_to "Регистрация", signup_path, class: "btn btn-lg btn-primary" %>
</div>

app/views/static_pages/show.html.erb
<% provide(:title, "Показать медведя") %>

<h1>Показать медведей</h1>
<p>Здесь будут медведи</p>

app/views/static_pages/upload.html.erb
<% provide(:title, "Загрузить медведя") %>

<h1>Загрузить медведя</h1>
<p>Здесь можно будет загружать медведей.</p>

app/views/users/new.html.erb
<% provide(:title, 'Регистрация') %>
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>